### ISSUE TITLE
local server

### ISSUE THREAD

**Issue by farvardin** [2dengine/love.js#2]
I've tried a play a little sample game (nothing fancy there, it works fine with https://schellingb.github.io/LoveWebBuilder/package) in the Brave Browser (based on chromium).

I got this error in the console:

```
love.js:9 Uncaught ReferenceError: SharedArrayBuffer is not defined
    at love.js:9:15375
    at s.onload (game.js:116:9)
```

my index.html is simply

```
<!doctype html>
<html lang="en-us">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width,user-scalable=no">
    <title>löve.js</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <canvas id="canvas"></canvas>
    <div id="spinner" class="pending"></div>
    <script src="player.js?g=mygame.love"></script>
  </body>
</html>
```

and the rest of this git repo is in the same folder which is served by apache.

**Comment by 2dengine** [comment]
Hello thank you for the bug reports.
I agree with you that the "SharedArrayBuffer" error message is not very descriptive.

This particular bug is a restriction introduced in modern browsers related to the "Cross-Origin" policy.
You need to set the appropriate HTTP headers on your server so that web assembly can load its external assets.
The included .htaccess file sets these headers automatically on most Apache servers (assuming that you have "mod_headers" enabled via "a2enmod headers").
Also, please make sure these headers are only altered for your love.js folder and not your entire website because that may lead to security issues.

**Comment by farvardin** [comment]
@2engine I had the .htaccess at the root of the  but mod_headers wasn't enabled. I've done it and reloaded apache but I get the same error...
It's on localhost without https, maybe I'll try to upload it somewhere behind a true domain name...

**Comment by 2dengine** [comment]
Are you sure that Apache is executing your .htaccess files? In the newer versions of Apache you need to have the AllowOverride directive enabled or your .htaccess files may be ignored altogether.

I will think about making the installation process easier, but as I said, this is caused by the headers sent by your server. Just make sure that your headers are set correctly and it will work. It should work with both HTTP and with HTTPS so you do not need a domain.

**Comment by farvardin** [comment]
Thank you for telling me about this AllowOverride directive... I read now it's enabled by default to "reduce the charge on the server" so it won't look for .htaccess files (which was an essential file for customising a server some time ago)... web used to be simpler back in the days :)

It's working now, I've replaced AllowOverride none by AllowOverride all in the dedicated section of /etc/apache2/apache2.conf and my simple example is running correctly! Thank you

![image](https://github.com/2dengine/love.js/assets/477243/db29e909-d792-4b92-bac1-faeea27e8145)

**Comment by 2dengine** [comment]
Great! Glad you got it working.
Just please be careful with the "Cross-Origin" policy settings because that could be used to allow embedding and executing external scripts on your page. 
Yes, web development has changed a lot. Security is a much greater concern nowadays so many of the server features that we are used to are now disabled by default.

**Comment by gphg** [comment]
You can skip the server http headers configuration if you build the game with compatibility set on. More information here:
https://github.com/Davidobot/love.js?tab=readme-ov-file#notes

This repository does not the compatibility version. I wish it has one, please make it happen @2dengine.

If you managed to get love.js installed via NodeJS and require to run your project locally for development purpose or testing with compatibility mode off, you can use my script here:
https://codeberg.org/garett/topgem/src/commit/fa8363888ceaf367c25160f2fac976b20e47b1db/extra/node/server.js (you have to configure the server path yourselves; be sure it points to build directory)

**Comment by 2dengine** [comment]
Hello again. I have added support for the optional compatibility flag as follows:

example.com/player/?g=mygame.love&c=1
Where "c=1" enables the compatibility mode.

The Cross-Origin-Policy requirements are related to running WebAssembly safely inside the browser. There is no simple way to "skip the HTTP headers configuration" - but rather it is important to understand the purpose of CORS and why it is used in this case.

**Comment by 2dengine** [comment]
Server-side setup it is not relevant to the repository.
